language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux

notifications:
  email: false
branches:
  only:
    - master

install:
  - pip install .

before_script:
  # See https://github.com/pywbem/pywbem/pull/1370/files and
  # https://github.com/pywbem/pywbem/issues/1371 for why we need
  # a specific old version of pytest-cov
  - pip install pytest pytest-cov==2.5.1

script:
  - pytest --cov=./

after_success:
  - pip install codecov
  - codecov
